### ISSUE TITLE
Connect Daigram

### ISSUE THREAD

**Issue by Ankitkj1999** [zoghlami-khalil/Sunrise#1]
I would be great for our understanding of the project if we can get the connection daigram of the circuit.

**Comment by zoghlami-khalil** [comment]
Hi @Ankitkj1999,

I didn't add the wiring diagram to the source files since I'm not sure if the diagram I have is correct and this was an old project.
Here is the diagram I found if you want to try it:


![Wiring Diagram-Sunchine](https://user-images.githubusercontent.com/76956031/193366234-ecddf95a-12d7-438c-bb58-edbef1d63870.png)
